In [ ]:
# Task 20: Sort Dataset Using Pandas

## Objective
Sort numerical and categorical columns in ascending and
descending order and demonstrate sorting by multiple columns.

## Deliverables
- Ascending sorting example
- Descending sorting example
- Categorical column sorting
- Multiple-column sorting
- Explanation of each sorting operation

In [1]:
import pandas as pd
import numpy as np

data = {
    "student_id": [
        1001, 1002, 1003, 1004, 1005, 1006,
        1007, 1008, 1009, 1010, 1011, 1012
    ],
    "name": [
        "Aarav", "Diya", "Kabir", "Ananya",
        "Ishaan", "Meera", "Rohan", "Sara",
        "Vivaan", "Aditi", "Arjun", "Nisha"
    ],
    "department": [
        "Computer Science", "Electronics", "Mechanical",
        "Computer Science", "Civil", "Electronics",
        "Mechanical", "Computer Science", "Civil",
        "Electronics", "Mechanical", "Computer Science"
    ],
    "age": [20, 21, 20, 22, 21, 20, 22, 21, 20, 22, 21, 20],
    "marks": [86, 91, 74, 95, 68, 88, 79, 93, 72, 84, 77, 90],
    "attendance": [92, 88, 79, 96, 72, 90, 85, 94, 80, 86, 75, 91]
}

df = pd.DataFrame(data)

print("Dataset created successfully!")
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

display(df)

Dataset created successfully!
Number of rows: 12
Number of columns: 6

    student_id    name        department  age  marks  attendance
0         1001   Aarav  Computer Science   20     86          92
1         1002    Diya       Electronics   21     91          88
2         1003   Kabir        Mechanical   20     74          79
3         1004  Ananya  Computer Science   22     95          96
4         1005  Ishaan             Civil   21     68          72
5         1006   Meera       Electronics   20     88          90
6         1007   Rohan        Mechanical   22     79          85
7         1008    Sara  Computer Science   21     93          94
8         1009  Vivaan             Civil   20     72          80
9         1010   Aditi       Electronics   22     84          86
10        1011   Arjun        Mechanical   21     77          75
11        1012   Nisha  Computer Science   20     90          91

In [2]:
print("STUDENTS SORTED BY MARKS — ASCENDING")

ascending_marks = df.sort_values(
    by="marks",
    ascending=True
)

display(ascending_marks)

STUDENTS SORTED BY MARKS — ASCENDING

    student_id    name        department  age  marks  attendance
4         1005  Ishaan             Civil   21     68          72
8         1009  Vivaan             Civil   20     72          80
2         1003   Kabir        Mechanical   20     74          79
10        1011   Arjun        Mechanical   21     77          75
6         1007   Rohan        Mechanical   22     79          85
9         1010   Aditi       Electronics   22     84          86
0         1001   Aarav  Computer Science   20     86          92
5         1006   Meera       Electronics   20     88          90
11        1012   Nisha  Computer Science   20     90          91
1         1002    Diya       Electronics   21     91          88
7         1008    Sara  Computer Science   21     93          94
3         1004  Ananya  Computer Science   22     95          96

In [3]:
print("STUDENTS SORTED BY MARKS — DESCENDING")

descending_marks = df.sort_values(
    by="marks",
    ascending=False
)

display(descending_marks)

STUDENTS SORTED BY MARKS — DESCENDING

    student_id    name        department  age  marks  attendance
3         1004  Ananya  Computer Science   22     95          96
7         1008    Sara  Computer Science   21     93          94
1         1002    Diya       Electronics   21     91          88
11        1012   Nisha  Computer Science   20     90          91
5         1006   Meera       Electronics   20     88          90
0         1001   Aarav  Computer Science   20     86          92
9         1010   Aditi       Electronics   22     84          86
6         1007   Rohan        Mechanical   22     79          85
10        1011   Arjun        Mechanical   21     77          75
2         1003   Kabir        Mechanical   20     74          79
8         1009  Vivaan             Civil   20     72          80
4         1005  Ishaan             Civil   21     68          72

In [4]:
print("DEPARTMENTS — ASCENDING ALPHABETICAL ORDER")

department_ascending = df.sort_values(
    by="department",
    ascending=True,
    kind="stable"
)

display(department_ascending)

DEPARTMENTS — ASCENDING ALPHABETICAL ORDER

    student_id    name        department  age  marks  attendance
4         1005  Ishaan             Civil   21     68          72
8         1009  Vivaan             Civil   20     72          80
0         1001   Aarav  Computer Science   20     86          92
3         1004  Ananya  Computer Science   22     95          96
7         1008    Sara  Computer Science   21     93          94
11        1012   Nisha  Computer Science   20     90          91
1         1002    Diya       Electronics   21     91          88
5         1006   Meera       Electronics   20     88          90
9         1010   Aditi       Electronics   22     84          86
2         1003   Kabir        Mechanical   20     74          79
6         1007   Rohan        Mechanical   22     79          85
10        1011   Arjun        Mechanical   21     77          75

In [5]:
print("DEPARTMENTS — DESCENDING ALPHABETICAL ORDER")

department_descending = df.sort_values(
    by="department",
    ascending=False,
    kind="stable"
)

display(department_descending)

DEPARTMENTS — DESCENDING ALPHABETICAL ORDER

    student_id    name        department  age  marks  attendance
2         1003   Kabir        Mechanical   20     74          79
6         1007   Rohan        Mechanical   22     79          85
10        1011   Arjun        Mechanical   21     77          75
1         1002    Diya       Electronics   21     91          88
5         1006   Meera       Electronics   20     88          90
9         1010   Aditi       Electronics   22     84          86
0         1001   Aarav  Computer Science   20     86          92
3         1004  Ananya  Computer Science   22     95          96
7         1008    Sara  Computer Science   21     93          94
11        1012   Nisha  Computer Science   20     90          91
4         1005  Ishaan             Civil   21     68          72
8         1009  Vivaan             Civil   20     72          80

In [6]:
print("MULTIPLE-COLUMN SORTING")
print("Department: Ascending | Marks: Descending")

multi_column_sort = df.sort_values(
    by=["department", "marks"],
    ascending=[True, False]
)

display(multi_column_sort)

MULTIPLE-COLUMN SORTING
Department: Ascending | Marks: Descending

    student_id    name        department  age  marks  attendance
8         1009  Vivaan             Civil   20     72          80
4         1005  Ishaan             Civil   21     68          72
3         1004  Ananya  Computer Science   22     95          96
7         1008    Sara  Computer Science   21     93          94
11        1012   Nisha  Computer Science   20     90          91
0         1001   Aarav  Computer Science   20     86          92
1         1002    Diya       Electronics   21     91          88
5         1006   Meera       Electronics   20     88          90
9         1010   Aditi       Electronics   22     84          86
6         1007   Rohan        Mechanical   22     79          85
10        1011   Arjun        Mechanical   21     77          75
2         1003   Kabir        Mechanical   20     74          79

In [7]:
print("MARKS DESCENDING, THEN ATTENDANCE DESCENDING")

marks_attendance_sort = df.sort_values(
    by=["marks", "attendance"],
    ascending=[False, False]
)

display(marks_attendance_sort)

MARKS DESCENDING, THEN ATTENDANCE DESCENDING

    student_id    name        department  age  marks  attendance
3         1004  Ananya  Computer Science   22     95          96
7         1008    Sara  Computer Science   21     93          94
1         1002    Diya       Electronics   21     91          88
11        1012   Nisha  Computer Science   20     90          91
5         1006   Meera       Electronics   20     88          90
0         1001   Aarav  Computer Science   20     86          92
9         1010   Aditi       Electronics   22     84          86
6         1007   Rohan        Mechanical   22     79          85
10        1011   Arjun        Mechanical   21     77          75
2         1003   Kabir        Mechanical   20     74          79
8         1009  Vivaan             Civil   20     72          80
4         1005  Ishaan             Civil   21     68          72

In [8]:
sorting_summary = pd.DataFrame({
    "Operation": [
        "Marks ascending",
        "Marks descending",
        "Department ascending",
        "Department descending",
        "Department ascending + marks descending"
    ],
    "Sorting column(s)": [
        "marks",
        "marks",
        "department",
        "department",
        "department, marks"
    ],
    "Ascending setting": [
        "True",
        "False",
        "True",
        "False",
        "[True, False]"
    ],
    "Number of records": [
        len(ascending_marks),
        len(descending_marks),
        len(department_ascending),
        len(department_descending),
        len(multi_column_sort)
    ]
})

display(sorting_summary)

,Operation,Sorting column(s),Ascending setting,Number of records
0,Marks ascending,marks,True,12
1,Marks descending,marks,False,12
2,Department ascending,department,True,12
3,Department descending,department,False,12
4,Department ascending + marks descending,"department, marks","[True, False]",12

In [9]:
df.to_csv("student_performance.csv", index=False)

print("student_performance.csv saved successfully.")

student_performance.csv saved successfully.

In [10]:
from google.colab import files

files.download("student_performance.csv")